### ISSUE TITLE
Please upgrade 

### ISSUE THREAD

**Issue by ahmedsamirdev** [TareqNewazShahriar/zero-degree#2]
"zero-degree": "3.1.0"
 "expo": "~46.0.16",
"react": "18.0.0",
    "react-native": "0.69.6",
    
 the package still rely on @unimodules/core which is deprecated and cause error when trying to install or any alternative to it

**Comment by TareqNewazShahriar** [comment]
Thanks for letting me know. I will check the versions and take necessary action.

**Comment by TareqNewazShahriar** [comment]
Oops, so you are talking about the Expo snack https://snack.expo.dev/@tareqshahriar/zero_degree. Packages updated.
